// Given two strings s and t which consist of only lowercase letters.
// String t is generated by random shuffling string s and then add one more letter at a random position.
// Find the letter that was added in t.
// Example:
// Input:
// s = "abcd"
// t = "abcde"
// Output:
// e
// Explanation:
// 'e' is the letter that was added.

/**
 * @param {string} s
 * @param {string} t
 * @return {character}
 */
var findTheDifference = function(s, t) {
    var slen = s.length,
        tlen = t.length;
    var map = {};
    for(var i = 0; i < slen; i++){   // push all the character of s in the map and it appearence times.
      if(s[i] in map) 
          map[s[i]]++;
      else
          map[s[i]] = 1;
    }
    
    for(var i = 0; i < tlen; i++){    
      if(t[i] in map)
          map[t[i]]--;
      else
          return t[i];
    }
    for(var i = 0; i <tlen; i++){
        if(map[t[i]] !== 0) return t[i];
    }
}
